In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Restaurant_Reviews.tsv',delimiter='\t',quoting=3)
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [27]:
dataset.shape

(1000, 2)

In [1]:
#cleaning the texts
import re
import nltk

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [5]:
from nltk.corpus import stopwords

In [6]:
from nltk.stem.porter import PorterStemmer

In [8]:
ps=PorterStemmer()
corpus=[]

In [15]:
for i in range(0,len(dataset)):
    review=re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    review=review.lower()
    review=review.split( )
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
x=cv.fit_transform(corpus).toarray()
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
x.shape

(1000, 1565)

In [29]:
y=dataset['Liked']
y.head()

0    1
1    0
2    0
3    1
4    1
Name: Liked, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB().fit(x_train,y_train)

In [34]:
y_predict=model.predict(x_test)
y_predict[0:10]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [37]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
cm

array([[72, 25],
       [22, 81]], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_predict)
print(ac)

0.765
