In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv('PM2.5.csv')
shape=df.shape
print(shape)

(9504, 28)


In [3]:
df.head()

IHBAS-CPCB  Dwarka-S8-DPCC  Sri-Aurobindo-Marg-DPCC  DTU-CPCB  \
0       26.55           26.00                    36.00     30.92   
1       22.12           29.25                    42.00     29.30   
2       42.55           30.75                    42.00     28.21   
3       30.73           34.25                    41.75     61.21   
4       20.18           36.75                    39.25     22.79   

   Okhla-Phase-2-DPCC  Alipur-DPCC  Aya-Nagar-IMD  Sonia-Vihar-DPCC  JNS-DPCC  \
0                52.0        39.50          25.54              40.0     43.75   
1                42.0        38.00          61.98              38.0     32.25   
2                37.0        24.75          49.71              47.0     26.50   
3                33.0        12.00          13.26              14.0     23.25   
4                23.5        13.00          15.85              28.0     19.00   

   Mundka-DPCC  ...  Punjabi-Bagh-DPCC  Jahangirpuri-DPCC  Bawana-DPCC  \
0         28.0  ...              37.50              50.25    27.000000   
1         27.0  ...              39.00              45.50    26.250000   
2         24.5  ...              41.00              32.50    24.000000   
3         26.5  ...              22.50              14.25    24.000000   
4         38.0  ...              32.25              10.75    31.779412   

   Narela-CPCB  Patparganj-DPCC  Rohini-DPCC  Anand-Vihar-DPCC  \
0        29.50            30.75         35.0             43.75   
1        28.75            37.50         29.0             32.50   
2        18.00            38.75         31.0             24.25   
3         8.00            28.00         56.0             22.75   
4        15.00            22.00         24.0             20.75   

   NSIT-Dwarka-CPCB  MDCNS-DPCC  Najafgarh-DPCC  
0             26.73   30.250000            29.0  
1             19.75   31.333333            31.5  
2             15.47   25.777778            29.0  
3             13.84   25.888889            35.0  
4             15.13   21.944444            40.0  

[5 rows x 28 columns]

In [4]:
dataset=df.dropna()

In [5]:
dataset.isnull().sum()

IHBAS-CPCB                 0
Dwarka-S8-DPCC             0
Sri-Aurobindo-Marg-DPCC    0
DTU-CPCB                   0
Okhla-Phase-2-DPCC         0
Alipur-DPCC                0
Aya-Nagar-IMD              0
Sonia-Vihar-DPCC           0
JNS-DPCC                   0
Mundka-DPCC                0
Pusa-DPCC                  0
Shadipur-CPCB              0
Vivek-Vihar-DPCC           0
Mandir-Marg-DPCC           0
Nehru-Nagar-DPCC           0
Wazirpur-DPCC              0
CRRI-Mathura-Road          0
RK-Puram-DPCC              0
Punjabi-Bagh-DPCC          0
Jahangirpuri-DPCC          0
Bawana-DPCC                0
Narela-CPCB                0
Patparganj-DPCC            0
Rohini-DPCC                0
Anand-Vihar-DPCC           0
NSIT-Dwarka-CPCB           0
MDCNS-DPCC                 0
Najafgarh-DPCC             0
dtype: int64

In [6]:
y=dataset['IHBAS-CPCB']
y.head()

0    26.55
1    22.12
2    42.55
3    30.73
4    20.18
Name: IHBAS-CPCB, dtype: float64

In [7]:
x=dataset.drop("IHBAS-CPCB", axis='columns')
x.head()

Dwarka-S8-DPCC  Sri-Aurobindo-Marg-DPCC  DTU-CPCB  Okhla-Phase-2-DPCC  \
0           26.00                    36.00     30.92                52.0   
1           29.25                    42.00     29.30                42.0   
2           30.75                    42.00     28.21                37.0   
3           34.25                    41.75     61.21                33.0   
4           36.75                    39.25     22.79                23.5   

   Alipur-DPCC  Aya-Nagar-IMD  Sonia-Vihar-DPCC  JNS-DPCC  Mundka-DPCC  \
0        39.50          25.54              40.0     43.75         28.0   
1        38.00          61.98              38.0     32.25         27.0   
2        24.75          49.71              47.0     26.50         24.5   
3        12.00          13.26              14.0     23.25         26.5   
4        13.00          15.85              28.0     19.00         38.0   

   Pusa-DPCC  ...  Punjabi-Bagh-DPCC  Jahangirpuri-DPCC  Bawana-DPCC  \
0      34.25  ...              37.50              50.25    27.000000   
1      35.00  ...              39.00              45.50    26.250000   
2      30.50  ...              41.00              32.50    24.000000   
3      18.50  ...              22.50              14.25    24.000000   
4      21.25  ...              32.25              10.75    31.779412   

   Narela-CPCB  Patparganj-DPCC  Rohini-DPCC  Anand-Vihar-DPCC  \
0        29.50            30.75         35.0             43.75   
1        28.75            37.50         29.0             32.50   
2        18.00            38.75         31.0             24.25   
3         8.00            28.00         56.0             22.75   
4        15.00            22.00         24.0             20.75   

   NSIT-Dwarka-CPCB  MDCNS-DPCC  Najafgarh-DPCC  
0             26.73   30.250000            29.0  
1             19.75   31.333333            31.5  
2             15.47   25.777778            29.0  
3             13.84   25.888889            35.0  
4             15.13   21.944444            40.0  

[5 rows x 27 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8,random_state=0)

In [9]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=reg.predict(x_train)
y_pred

array([ 24.37983359, 128.6610338 , 236.29818454, ..., 209.25243245,
       102.10520562, 100.98450998])

In [11]:
from sklearn.metrics import r2_score

In [12]:
r2_score(y_train, y_pred)

0.8712826471776092

In [13]:
y_pred_test=reg.predict(x_test)
y_pred_test

array([ 49.07210762,  18.96632864,  36.27068905, ..., 260.81065828,
        57.55128175,  18.05870175])

In [14]:
r2_score(y_test, y_pred_test)

0.8488605159612111

In [15]:
from sklearn import svm
regr = svm.SVR(kernel='rbf')
regr.fit(x_train,y_train)

SVR()

In [16]:
y_predicted=regr.predict(x_train)
y_predicted

array([ 24.52829052, 121.21019173, 199.21735073, ..., 172.1914309 ,
       102.18841301, 113.57643217])

In [17]:
r2_score(y_train, y_predicted)

0.7180561616113852

In [18]:
y_predicted_test=regr.predict(x_test)
y_predicted_test

array([ 44.54544798,  18.33033169,  35.72395449, ..., 218.62805744,
        71.05099482,  18.70824507])

In [19]:
r2_score(y_test, y_predicted_test)

0.6810791738643895

In [20]:
from sklearn import tree
clf = tree.DecisionTreeRegressor()
clf = clf.fit(x_train,y_train)

In [21]:
y_predicted_tree=clf.predict(x_train)
y_predicted_tree

array([ 28.12, 145.25, 269.12, ..., 161.75,  80.7 , 124.4 ])

In [22]:
r2_score(y_train, y_predicted_tree)

1.0

In [23]:
y_predicted_test_tree=clf.predict(x_test)
y_predicted_test_tree

array([ 61.42      ,  14.38      ,  50.62      , ..., 330.95      ,
        42.48411765,   7.32      ])

In [24]:
r2_score(y_test, y_predicted_test_tree)

0.7564396720587567