In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x=dataset.drop(["Exited","RowNumber","CustomerId","Surname"],axis=1)
y=dataset['Exited']

In [4]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encoder_x=LabelEncoder()
x['Geography']=label_encoder_x.fit_transform(x['Geography'])

label_encoder_y=LabelEncoder()
x['Gender']=label_encoder_y.fit_transform(x['Gender'])

In [6]:
x['Geography'].unique()

array([0, 2, 1])

In [7]:
x['Gender'].unique()

array([0, 1])

In [9]:
ohe=OneHotEncoder()

In [10]:
ohe_df=pd.DataFrame(ohe.fit_transform(x[['Geography']]).toarray())
ohe_df

0    1    2
0     1.0  0.0  0.0
1     0.0  0.0  1.0
2     1.0  0.0  0.0
3     1.0  0.0  0.0
4     0.0  0.0  1.0
...   ...  ...  ...
9995  1.0  0.0  0.0
9996  1.0  0.0  0.0
9997  1.0  0.0  0.0
9998  0.0  1.0  0.0
9999  1.0  0.0  0.0

[10000 rows x 3 columns]

In [11]:
X=x.join(ohe_df)
X=X.drop("Geography",axis="columns")
X.shape

(10000, 12)

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(X_train)
x_test=sc.fit_transform(X_test)

C:\Users\amitb\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\amitb\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\amitb\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\amitb\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [16]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -1.01460667,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  0.98560362,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ..., -1.01460667,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ..., -1.01460667,
         1.75486502, -0.57369368]])

In [17]:
y_train

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

In [18]:
import keras

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
classifier=Sequential([
    keras.layers.Dense(6,input_shape=(12,),activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

In [21]:
classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [22]:
classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 5s 1ms/step - loss: 0.5155 - accuracy: 0.7629
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4426 - accuracy: 0.8016
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4225 - accuracy: 0.8127
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4056 - accuracy: 0.8231
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3894 - accuracy: 0.8365
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3745 - accuracy: 0.8465
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3640 - accuracy: 0.8525
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3573 - accuracy: 0.8543
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3529 - accuracy: 0.8579
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3504 - accura

800/800 [==============================] - 1s 1ms/step - loss: 0.3387 - accuracy: 0.8610
Epoch 82/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3392 - accuracy: 0.8644
Epoch 83/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3392 - accuracy: 0.8644
Epoch 84/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3389 - accuracy: 0.8639
Epoch 85/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3388 - accuracy: 0.8645
Epoch 86/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3390 - accuracy: 0.8659
Epoch 87/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 0.8629
Epoch 88/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3390 - accuracy: 0.8640
Epoch 89/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3389 - accuracy: 0.8622
Epoch 90/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3387 - accuracy: 

In [27]:
classifier.evaluate(x_test,y_test)

63/63 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8605


[0.33553680777549744, 0.8604999780654907]

In [34]:
y_predicted=classifier(x_test)
y_predicted=(y_predicted>0.5)
y_predicted[:10]

<tf.Tensor: shape=(10, 1), dtype=bool, numpy=
array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])>

In [35]:
y_test[:10]

9394    0
898     1
2398    0
5906    0
2343    0
8225    1
5506    0
6451    0
2670    1
3497    1
Name: Exited, dtype: int64

In [38]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predicted)
cm

array([[1530,   65],
       [ 214,  191]], dtype=int64)